// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCMXu8H5L3aSsOF8uUqRknJxhLbKcHyU',
    appId: '1:250975612037:web:bc78ad5a971b1a55280dec',
    messagingSenderId: '250975612037',
    projectId: 'tablefinder-d7f61',
    authDomain: 'tablefinder-d7f61.firebaseapp.com',
    storageBucket: 'tablefinder-d7f61.appspot.com',
    measurementId: 'G-PP9T3BPNLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LBeL4drwthIBe0rOg50qotzAq40gso4',
    appId: '1:250975612037:android:828befb9c1753099280dec',
    messagingSenderId: '250975612037',
    projectId: 'tablefinder-d7f61',
    storageBucket: 'tablefinder-d7f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg7ixpEa2SsdIvht3k2sEGka1DCSkEpCk',
    appId: '1:250975612037:ios:500b5d695e7061e5280dec',
    messagingSenderId: '250975612037',
    projectId: 'tablefinder-d7f61',
    storageBucket: 'tablefinder-d7f61.appspot.com',
    iosBundleId: 'online.tablefinder.customer',
  );
}
